apiVersion: v1
kind: ConfigMap
metadata:
  name: payment
  namespace: roboshop
  labels:
    project: roboshop
    teir: backend
    component: payment
data:
  CART_HOST: cart
  CART_PORT: "8080"
  USER_HOST: user
  USER_PORT: "8080"
  AMQP_HOST: rabbitmq
  AMQP_USER: roboshop
  AMQP_PASS: roboshop123

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: roboshop
  labels:
    project: roboshop
    teir: backend
    component: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      teir: backend
      component: payment
  template:
    metadata:
      name: payment
      labels:
        project: roboshop
        teir: backend
        component: payment
    spec:
      containers:
        - name: payment
          image: dkrish194/payment:3.0.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "500m"
              memory: "500Mi"
            limits:
              cpu: "500m"
              memory: "500Mi"
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            periodSeconds: 10
            failureThreshold: 10
          envFrom:
            - configMapRef:
                name: payment
---
apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: roboshop
  labels:
    project: roboshop
    teir: backend
    component: payment
spec:
  type: ClusterIP
  selector:
    project: roboshop
    teir: backend
    component: payment
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
