apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping
  namespace: roboshop
  labels:
    project: roboshop
    teir: backend
    component: shipping
data:
  CART_ENDPOINT: "cart:8080"
  DB_HOST: mysql

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
  labels:
    project: roboshop
    teir: backend
    component: shipping
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      teir: backend
      component: shipping
  template:
    metadata:
      name: shipping
      labels:
        project: roboshop
        teir: backend
        component: shipping
    spec:
      containers:
        - name: shipping
          image: dkrish194/shipping:3.0.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "500m"
              memory: "500Mi"
            limits:
              cpu: "500m"
              memory: "500Mi"
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            periodSeconds: 10
            failureThreshold: 10
          envFrom:
            - configMapRef:
                name: shipping
---
apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: roboshop
  labels:
    project: roboshop
    teir: backend
    component: shipping
spec:
  type: ClusterIP
  selector:
    project: roboshop
    teir: backend
    component: shipping
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
