apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: roboshop
  name: mongodb
  labels:
    project: roboshop
    teir: db
    component: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      teir: db
      component: mongodb
  template:
    metadata:
      name: podname
      labels:
        project: roboshop
        teir: db
        component: mongodb
    spec:
      containers:
        - name: mongodb
          image: dkrish194/mongodb:3.0.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "300m"
              memory: "300Mi"
            limits:
              cpu: "300m"
              memory: "300Mi"
---
apiVersion: v1
kind: Service
metadata:
  namespace: roboshop
  name: mongodb
  labels:
      project: roboshop
      teir: db
      component: mongodb
spec:
  selector:
    project: roboshop
    teir: db
    component: mongodb
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP






