apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: roboshop
  labels:
    project: roboshop
    teir: db
    component: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      teir: db
      component: mysql
  template:
    metadata:
      name: mysql
      labels:
        project: roboshop
        teir: db
        component: mysql
    spec:
      containers:
        - name: mysql
          image: dkrish194/mysql:3.0.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "800m"
              memory: "800Mi"
            limits:
              cpu: "800m"
              memory: "800Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
  labels:
    project: roboshop
    teir: db
    component: mysql
spec:
  selector:
    project: roboshop
    teir: db
    component: mysql
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
