apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    project: roboshop
    teir: backend
    component: catalogue
data:
  MONGO: "true"
  MONGO_URL: "mongodb://mongodb:27017/catalogue"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    project: roboshop
    teir: backend
    component: catalogue
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      teir: backend
      component: catalogue
  template:
    metadata:
      name: catalogue
      labels:
        project: roboshop
        teir: backend
        component: catalogue
    spec:
      containers:
        - name: catalogue
          image: dkrish194/catalogue:3.0.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "500m"
              memory: "500Mi"
            limits:
              cpu: "500m"
              memory: "500Mi"
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            periodSeconds: 10
            failureThreshold: 10
          envFrom:
            - configMapRef:
                name: catalogue


---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    project: roboshop
    teir: backend
    component: catalogue
spec:
  selector:
    project: roboshop
    teir: backend
    component: catalogue
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP






