apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: roboshop
  labels:
    project: roboshop
    teir: db
    component: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      teir: db
      component: redis
  template:
    metadata:
      labels:
        project: roboshop
        teir: db
        component: redis
    spec:
      containers:
        - name: redis
          image: dkrish194/redis:2.0.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "300m"
              memory: "300Mi"
            limits:
              cpu: "300m"
              memory: "300Mi"
---
apiVersion: v1
kind: Service
metadata:
  namespace: roboshop
  name: redis
  labels:
    project: roboshop
    teir: db
    component: redis
spec:
  selector:
    project: roboshop
    teir: db
    component: redis
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP







